name: Tiny House Renters
layout_spectrum: 0.9297769340684656
typography_spectrum: 0.09191271426340583
analytics:
  google: UA-99647944-1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.9980397661019227
  lightness: 0.841747966783195
  saturation: 0.3155867985564072
  rhythmicContrast: 0.5975235728907519
title: Home Is Where Your Hreat Is.
description: ''
author:
  name: DC Multimedia Group
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/141528eaf618707068d6ad025386615a350d6efa.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/141528eaf618707068d6ad025386615a350d6efa.jpg
    metadata:
      '@type': MediaObject
      '@context': 'http://schema.org'
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/7ab2015b4946247cafa54ff5b2ab0c33/noop.jpeg?input=http%3A%2F%2Fhgtvhome.sndimg.com%2Fcontent%2Fdam%2Fimages%2Fhgtv%2Ffullset%2F2015%2F10%2F13%2F2%2FCI_Wheelhaus-wedge-tiny-house-exterior.jpg.rend.hgtvcom.616.462.jpeg
      keywords: []
      publisher:
        name: .s3-us-west-2.amazonaws.com
        domain: imgflo.herokuapp.com
        url: 'https://s3-us-west-2.amazonaws.com'
      author: []
      starred: false
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
