layout_spectrum: 0.9297769340684656
typography_spectrum: 0.09191271426340583
color:
  brandStrength: 0.9980397661019227
  lightness: 0.841747966783195
  saturation: 0.3155867985564072
  rhythmicContrast: 0.5975235728907519
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: Tiny House Renters
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/141528eaf618707068d6ad025386615a350d6efa.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/141528eaf618707068d6ad025386615a350d6efa.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/7ab2015b4946247cafa54ff5b2ab0c33/noop.jpeg?input=http%3A%2F%2Fhgtvhome.sndimg.com%2Fcontent%2Fdam%2Fimages%2Fhgtv%2Ffullset%2F2015%2F10%2F13%2F2%2FCI_Wheelhaus-wedge-tiny-house-exterior.jpg.rend.hgtvcom.616.462.jpeg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Tiny House Renters
description: ''
url: 'https://tinyhouserenters.com'
author:
  name: DC Multimedia Group
github: true
analytics:
  google: UA-99647944-1
